import React, {useState,useEffect,lazy,Suspense} from 'react';
import WorkGallery from './WorkGallery.jsx';
import HeroFileStack from './HeroFileStack.jsx';
import useSoftReveals from './useSoftReveals.js';
import {PixelStar} from './PixelMarks.jsx';
import {createRoot} from 'react-dom/client';
import './style.css';
import './gallery.css';
import './sketchbook.css';
import './motion-theme.css';
import './pixel-theme.css';
import './pixel-cursors.css';

const PixelSnow=lazy(()=>import('./PixelSnow.jsx'));
const art=import.meta.env.BASE_URL+'art/';
const asset=(name)=>window.__PORTFOLIO_ART__?.[name] || art+name;
const jobs=[['2025.07 — 至今','巨星传奇','IP 设计师 · 角色原画','周同学形象升级、视觉图库搭建、品牌联名与潮玩产品监修。'],['2023.07 — 2025.07','Soul APP','原画师 · IP 与潮玩','探索多种美术风格，设计数字形象与衍生品，构建团队 AI 绘画工作流。'],['2022.03 — 2023.07','极链科技','潮玩设计师','IP 角色、盲盒与明星周边设计，参与模型制作与运营插画。'],['2020.07 — 2020.12','三只松鼠','产品策划','文创与周边创意策划，跟进打样、包装印刷与产品交付。']];
function App(){
 useSoftReveals();
 const [copied,setCopied]=useState(false),[active,setActive]=useState('home');
 useEffect(()=>{const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)}),{rootMargin:'-20% 0px -55% 0px'});document.querySelectorAll('main>section').forEach(el=>obs.observe(el));return()=>obs.disconnect()},[]);
 async function copyEmail(){try{await navigator.clipboard.writeText('2568808450@qq.com');setCopied(true);setTimeout(()=>setCopied(false),2400)}catch{window.location.href='mailto:2568808450@qq.com'}}
 return <><Suspense fallback={null}><PixelSnow/></Suspense><header className="nav"><a className="wordmark" href="#home" aria-label="返回首页"><span className="brand-star"><PixelStar/></span> JIAMING<span className="brand-dot">.</span></a><nav aria-label="主导航">{[['home','首页'],['about','关于我'],['work','精选作品'],['skills','我的优势']].map(([id,label])=><a key={id} className={active===id?'active':''} href={'#'+id}>{label}</a>)}</nav><a className="nav-contact" href="#contact">聊聊新灵感 <span>✧</span></a></header>
 <main><section id="home" className="hero"><div className="hero-grain"/><div className="hero-topline">ILLUSTRATION & IP DESIGN <span>PORTFOLIO / 2026</span></div><div className="hero-copy"><span className="paper-label">JIAMING’S CREATIVE NOTES</span><div className="eyebrow"><span/> 你好，我是袁嘉明</div><h1>给想象力<br/>一个<span className="dream-word">可爱的</span><br/><span className="world-word">小世界<span className="title-star"><PixelStar/></span></span></h1><p>插画设计师 / IP 设计师<br/>用色彩讲故事，把天马行空变成触手可及的快乐。</p><a className="pill primary" href="#work">进入我的作品世界 <span>✧</span></a></div><HeroFileStack asset={asset}/><div className="hero-bottom"><a href="#about">向下探索 <span>↓</span></a><span>让每一个角色，都有自己的故事。</span></div></section>
 <div className="ribbon" aria-hidden="true"><span>COLORFUL IDEAS</span> ✦ <span>可爱是认真创造的</span> ✦ <span>LITTLE CHARACTERS, BIG DREAMS</span> ✦ <span>把灵感画成故事</span> ✦</div>
 <section id="about" className="section about"><div className="section-heading"><div><span className="section-index">01 / ABOUT ME</span><h2>想象很多，<br/>也认真让它发生<span className="pink-star"><PixelStar/></span></h2></div><span className="hand-note">A little about me</span></div><div className="about-paper"><div className="about-grid"><div className="portrait-card"><div className="portrait-image"><img src={asset('portrait-current.webp')} alt="袁嘉明的个人头像" loading="lazy"/></div><div className="portrait-name">袁嘉明 <span>JIAMING YUAN</span></div><p>插画 / IP / 潮玩设计</p><span className="portrait-pin">✦</span></div><div className="bio"><span className="mini-label">让角色有温度，让设计有生命力。</span><h3>你好呀，我是嘉明。</h3><p>拥有 6 年设计经验，擅长用二次元、可爱风、厚涂等不同视觉语言，为角色赋予鲜明的性格与故事。</p><p>从 IP 形象开发、视觉图库搭建，到盲盒、毛绒与授权产品落地，我喜欢把一个小小的灵感，慢慢变成完整的世界。曾参与周同学 IP 升级，以及迪士尼、三丽鸥等 IP 合作项目。</p><div className="bio-tags"><span>角色与插画</span><span>IP 视觉体系</span><span>潮玩与衍生品</span></div><div className="bio-contact"><a href="mailto:2568808450@qq.com">2568808450@qq.com</a><a href="tel:17612119839">176 1211 9839</a></div></div></div><div className="stats"><div><strong>6<span>年</span></strong><p>设计与商业项目经验</p></div><div><strong>2500<span>万+</span></strong><p>参与 / 主导项目累计商业收入</p></div><div><strong>33<span>%</span></strong><p>AI 工作流节省单图绘制时间</p></div><div><strong>6<span>款</span></strong><p>周同学玻璃钢大娃系列创作</p></div></div><div className="journey"><div className="journey-title"><span className="section-index">MY JOURNEY</span><h3>一路画来</h3><p>北京理工大学 · 产品设计 / 工商管理双学位<br/>2016 — 2020</p></div><div className="timeline">{jobs.map(([date,company,role,desc])=><div className="job" key={company}><span className="job-date">{date}</span><div><h4>{company}<span>{role}</span></h4><p>{desc}</p></div></div>)}</div></div></div></section>
 <section id="work" className="section work"><div className="section-heading"><div><span className="section-index">02 / SELECTED WORKS</span><h2>一些，喜欢的世界<span className="pink-star"><PixelStar/></span></h2></div><p>每一个小世界，<br/>都是一次认真而自由的想象。</p></div><WorkGallery asset={asset}/></section>
 <section id="skills" className="section skills"><div className="section-heading"><div><span className="section-index">03 / WHAT I BRING</span><h2>可爱的背后，<br/>有认真打磨的能力</h2></div><span className="hand-note">More than cute!</span></div><div className="skills-grid">{[['✳','01','从 0 到 1 的角色创造','IP 形象开发 / 世界观 / 视觉图库','把抽象概念变成鲜明角色，建立可持续延展的视觉语言，让 IP 在不同场景下都保持自己的个性。'],['✧','02','多种风格，同样有趣','二次元 / Q 版 / 厚涂 / 韩风','理解不同 IP 与品牌的视觉要求，快速切换画风。参与迪士尼、三丽鸥等合作，兼顾辨识度与交付标准。'],['❋','03','让好设计真正落地','盲盒 / 毛绒 / 衍生品 / 监修','熟悉从原画到量产的过程，配合 3D 建模、打样与产品监修，让画面中的细节也能成为实物的魅力。'],['✦','04','为创作找到更好的方法','ComfyUI / 模型训练 / 工作流','独立部署、训练并优化 AI 绘画工作流，将方法沉淀为团队可复用的工具，单图平均节省 33% 绘制时间。']].map(([symbol,n,title,tags,desc])=><article className="skill-card" key={n}><div className="skill-top"><span>{symbol}</span><small>{n}</small></div><h3>{title}</h3><span className="skill-tags">{tags}</span><p>{desc}</p></article>)}</div><div className="tool-line"><span>MY CREATIVE TOOLKIT</span><div>Photoshop · Illustrator · Procreate · SAI · ComfyUI</div></div></section>
 <section id="contact" className="contact"><div className="contact-sheet"><span className="letter-tab">A NOTE TO YOU</span><span className="contact-spark"><PixelStar/></span><span className="section-index">04 / LET'S CREATE SOMETHING</span><h2>下一个小世界，<br/>想和你一起创造<span>。</span></h2><p>插画创作、IP 设计、潮玩与衍生品合作，<br/>或是一个还没有名字的灵感，都欢迎来聊聊。</p><a className="contact-email" href="mailto:2568808450@qq.com">2568808450@qq.com <span>✧</span></a><div className="contact-actions"><button className="pill" onClick={copyEmail}>{copied?'邮箱已复制 ✓':'复制邮箱'}</button><a className="pill" href="tel:17612119839">176 1211 9839</a></div><span className="copy-status" role="status">{copied?'期待收到你的新灵感。':''}</span></div><footer><a className="wordmark" href="#home">✦ JIAMING.</a><span>© 2026 袁嘉明 · 用想象力认真创造</span><a href="#home">回到顶部 ↑</a></footer></section></main>
 </>;
}
createRoot(document.getElementById('root')).render(<App/>);

